package com.japanesestudy.app.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

import lombok.extern.slf4j.Slf4j;

@Configuration
@Slf4j
public class DatabaseInitializer {

    @Bean
    public CommandLineRunner ensureSchema(JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                try {
                    jdbcTemplate.queryForList("SELECT 1 FROM users LIMIT 1");
                    log.info("Table 'users' exists.");
                } catch (org.springframework.dao.DataAccessException e) {
                    log.warn("Table 'users' not found. Attempting manual creation...");
                    String sql = """
                        CREATE TABLE IF NOT EXISTS users (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(255) NOT NULL UNIQUE,
                            password VARCHAR(255) NOT NULL,
                            role VARCHAR(255) NOT NULL
                        );
                    """;
                    jdbcTemplate.execute(sql);
                    log.info("Created table 'users' manually.");
                }
            } catch (org.springframework.dao.DataAccessException ex) {
                log.error("Failed to check/create schema: " + ex.getMessage());
            }
        };
    }
}
