package com.japanesestudy.app.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import lombok.extern.slf4j.Slf4j;

@Configuration
@Slf4j
public class DatabaseInitializer {

    // On some platforms, ddl-auto=update fails to create the initial table if the DB is truly empty.
    // This runner serves as a safety net.
    @Bean
    public CommandLineRunner ensureSchema(JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                // Determine if we need to create the users table manually (Postgres/H2 compatible SQL)
                // Note: Hibernate usually handles this, but "Relation does not exist" suggests it failed.
                
                // Try selecting to see if it exists
                try {
                    jdbcTemplate.queryForList("SELECT 1 FROM users LIMIT 1");
                    log.info("Table 'users' exists.");
                } catch (Exception e) {
                    log.warn("Table 'users' not found. Attempting manual creation...");
                    
                    // Simple create statement for users if missing
                    // Compatible with H2 and Postgres (IDENTITY vs SERIAL is handled by Spring typically, but raw SQL needs care)
                    // We'll rely on a generic standard SQL.
                     
                    String sql = """
                        CREATE TABLE IF NOT EXISTS users (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(255) NOT NULL UNIQUE,
                            password VARCHAR(255) NOT NULL,
                            role VARCHAR(255) NOT NULL
                        );
                    """;
                    jdbcTemplate.execute(sql);
                    log.info("Created table 'users' manually.");
                }

            } catch (Exception ex) {
                log.error("Failed to check/create schema: " + ex.getMessage());
                // Don't re-throw, let Hibernate try the rest
            }
        };
    }
}
