CREATE TABLE IF NOT EXISTS course_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    access_level VARCHAR(16) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_course_access_course_user UNIQUE (course_id, user_id),
    CONSTRAINT fk_course_access_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_course_access_user FOREIGN KEY (user_id) REFERENCES users(id)
);
