ALTER TABLE courses ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE topics ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE study_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
